Info:     Reading ABAQUS from /home/km262911/IFAM_local/01_Drug_Eluting_Heart_Stents/10_Soft_tissue_modeling/01_Codes/plaque_growth/plaque_growth/in/nonlinear_reac_diff2.inp using /opt/soft/hyperworks/2017/altair/io/model_readers/feinput/bin/linux64/abaqus on 06-23-2020 22:33:43.
Warning:  Unsupported information found in input deck
          Resolution:  Unsupported text written to file: nonlinear_reac_diff2.inp.hmx
Warning:  Unsupported information found in the input deck.
          Resolution:  Unsupported text is moved to control cards. Check help for further information.
Warning:  Option INTERNAL is not supported for *ELSET card
          Resolution:  This option is skipped. You have to edit the deck to include this back.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Plots.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 3 warnings.
Info:     Translation Complete.
Info:     Reading ABAQUS from /home/km262911/IFAM_local/01_Drug_Eluting_Heart_Stents/10_Soft_tissue_modeling/01_Codes/plaque_growth/plaque_growth/in/nonlinear_reac_diff3.inp using /opt/soft/hyperworks/2017/altair/io/model_readers/feinput/bin/linux64/abaqus on 06-24-2020 00:23:06.
Warning:  Unsupported information found in input deck
          Resolution:  Unsupported text written to file: nonlinear_reac_diff3.inp.hmx
Warning:  Unsupported information found in the input deck.
          Resolution:  Unsupported text is moved to control cards. Check help for further information.
Warning:  Option INTERNAL is not supported for *ELSET card
          Resolution:  This option is skipped. You have to edit the deck to include this back.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Plots.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Parameters.

Summary:  Feinput finished with 0 errors and 3 warnings.
Info:     Translation Complete.
Info:     Reading ABAQUS from /home/km262911/IFAM_local/01_Drug_Eluting_Heart_Stents/10_Soft_tissue_modeling/01_Codes/plaque_growth/plaque_growth/in/nonlinear_reac_diff3.inp using /opt/soft/hyperworks/2017/altair/io/model_readers/feinput/bin/linux64/abaqus on 06-24-2020 01:04:32.
Warning:  Unsupported information found in input deck
          Resolution:  Unsupported text written to file: nonlinear_reac_diff3.inp0.hmx
Warning:  Unsupported information found in the input deck.
          Resolution:  Unsupported text is moved to control cards. Check help for further information.
Warning:  Option INTERNAL is not supported for *ELSET card
          Resolution:  This option is skipped. You have to edit the deck to include this back.
Info:     Processing Modules.
Info:     Processing Cards.
Info:     Processing System Collectors.
Info:     Processing Systems.
Info:     Processing Nodes.
Info:     Processing Materials.
Info:     Processing Properties.
Info:     Processing Components.
Info:     Processing Groups.
Info:     Processing Elements.
Info:     Processing Load Collectors.
Info:     Processing Equations.
Info:     Processing Loads.
Info:     Processing Assemblies.
Info:     Processing Curves.
Info:     Processing Plots.
Info:     Processing Sets.
Info:     Processing Output Blocks.
Info:     Processing Load Steps.
Info:     Processing Plys.
Info:     Processing Laminates.
Info:     Processing Beamsectcols.
Info:     Processing Beamsections.
Info:     Processing Optitableentrs.
Info:     Processing Tags.
Info:     Processing Contactsurfs.
Info:     Processing Transformations.
Info:     Processing Positions.
Info:     Processing Parameters.

Warning:  Control Card Title already exists    in database.
          Resolution:  Control Card was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Control Card Preprint already exists    in database.
          Resolution:  Control Card was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Control Card UNSUPPORTED_CARDS_START already exists    in database.
          Resolution:  Control Card was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Control Card UNSUPPORTED_CARDS already exists    in database.
          Resolution:  Control Card was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Warning:  Attribute read for a Control Card which has been ignored.
          Resolution:  Attribute was ignored.
Summary:  Feinput finished with 0 errors and 26 warnings.
Info:     Translation Complete.
